Repository Josephrp/adapt-a-rag, pull requests merged in 2024-03, with the labels that each got.

#12 Anthropic generation of synthetic data
  anthropic_generation.py
  example.env
  requirements.txt
Labels: enhancement

#7 Adapt-a-Rag: Adaptive Retrieval-Augmented Application
  README.md
  add_your_files_here/.example
  anthropic_generation.py
  app.py
  example.env
  ragutils.py
  requirements.txt
Labels: help wanted, good first issue

#25 Adapt-a-Rag: Adaptive Retrieval-Augmented Application
  app.py
Labels: enhancement, help wanted, good first issue
